#densepose_csv_path: "/mnt/comp/code/nips19/data/exercise_data/exercise_dataset/denseposed_csv/denseposed_instance_level_test_split.csv"
#data_root : "/mnt/comp/code/nips19/data/exercise_data/exercise_dataset"
data_root : "/export/home/sabraun/projects/gcpr_2020/lmdis-rep/data/PennAction"
densepose_csv_path : "/export/home/sabraun/projects/gcpr_2020/lmdis-rep/data/PennAction/denseposed_csv/denseposed_jumping_jacks_test.csv"
data_fname_col : "relative_denseposed_file_path_"

segmentation_algorithm_args:
  var : 0.01
  n_steps : 5

n_inferred_parts : 25

dp_semantic_remap_dict : {
  "arms" : ['left_upper_arm1',
            'left_upper_arm2',
           'right_upper_arm1',
           'right_upper_arm2',
           'left_lower_arm1',
           'right_lower_arm1',
           'left_lower_arm2',
           'right_lower_arm2',
           'right_hand',
           'left_hand'
          ],
  "legs" : [
      'back_upper_front_leg',
      'back_upper_left_leg',
      'right_upper_leg',
      'left_upper_leg',
      'back_right_lower_leg',
      'back_left_lower_leg',
      'right_lower_leg',
      'left_lower_leg',
  ],
  'head': ['left_head', 'right_head'],
  'feet': ['left_foot', 'right_foot'],
  'torso': ['chest', "back"],
  'background' : ['background']
}